// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'start-here/create-your-ai-support-agent',
        'start-here/add-your-ai-agent-to-your-website',
        'start-here/add-your-ai-agent-to-your-website-shopify',
        'start-here/add-your-ai-agent-to-your-website-wordpress',
        'start-here/add-your-ai-agent-to-your-website-zendesk',
        'start-here/how-long-does-it-take-to-set-up',
        'start-here/video-tutorials',
        'start-here/full-product-demo',
        'start-here/support',
        'start-here/what-is-an-ai-customer-support-agent',
        'start-here/what-is-an-ai-customer-support-agent-what-are-the-benefits-of-using-my-askai',
        'start-here/what-is-an-ai-customer-support-agent-who-is-this-for',
        'start-here/reviews'
      ]
    },
    {
      type: 'category',
      label: 'Account Management',
      items: [
        'account-management/affiliate-program',
        'account-management/billing',
        'account-management/billing-cancel-subscription',
        'account-management/billing-change-plan',
        'account-management/billing-discounts',
        'account-management/billing-download-an-invoice',
        'account-management/billing-refunds',
        'account-management/billing-tax',
        'account-management/billing-update-payment-card',
        'account-management/limits',
        'account-management/limits-conversations',
        'account-management/limits-exceeding-limits',
        'account-management/pricing---plans',
        'account-management/reselling---whitelabelling',
        'account-management/user-access',
        'account-management/user-access-reset-login-password',
        'account-management/user-access-setting-a-password-for-your-account',
        'account-management/your-profile',
        'account-management/your-profile-changing-your-email',
        'account-management/your-profile-close-your-account'
      ]
    },
    {
      type: 'category',
      label: 'Features',
      items: [
        'features/ai-answers-on-your-content',
        'features/channels',
        'features/channels-chrome-extension',
        'features/channels-freshchat',
        'features/channels-freshdesk',
        'features/channels-gorgias',
        'features/channels-hubspot',
        'features/channels-intercom',
        'features/channels-intercom-human-handover-workflows',
        'features/channels-live-chat-channels-feature-comparison',
        'features/channels-microsoft-teams',
        'features/channels-slack',
        'features/channels-zapier',
        'features/channels-zendesk',
        'features/channels-zendesk-zendesk-messaging',
        'features/channels-zendesk-zendesk-tagging---sentiment',
        'features/channels-zendesk-zendesk-tickets',
        'features/channels-zoho-salesiq',
        'features/connections',
        'features/connections-authorizations',
        'features/conversation-ratings-csat',
        'features/customization',
        'features/email-assistant',
        'features/file-uploads',
        'features/human-handover',
        'features/improve---custom-answers',
        'features/insights',
        'features/insights-conversation-insight-notifications',
        'features/languages-and-localization',
        'features/lead-email-capture',
        'features/private-internal-mode',
        'features/remove-branding',
        'features/shopify',
        'features/site-search',
        'features/sitesync-adding-and-syncing-your-website-content',
        'features/starter-actions',
        'features/team-access',
        'features/user-data-api-and-api-actions',
        'features/user-data-api-and-api-actions-user-data-api-setup'
      ]
    },
    {
      type: 'category',
      label: 'API Documentation',
      items: [
        'api-documentation/api-docs-introduction',
        'api-documentation/chat-api',
        'api-documentation/query-api',
        'api-documentation/user-data-api'
      ]
    },
    {
      type: 'category',
      label: 'Security & Privacy',
      items: [
        'security-privacy/security',
        'security-privacy/security-on-premise',
        'security-privacy/security-openai-api-keys',
        'security-privacy/security-soc-2',
        'security-privacy/privacy',
        'security-privacy/privacy-openai',
        'security-privacy/privacy-regulations',
        'security-privacy/privacy-regulations-gdpr-compliance',
        'security-privacy/privacy-regulations-hipaa',
        'security-privacy/privacy-your-content',
        'security-privacy/privacy-your-data'
      ]
    },
    {
      type: 'category',
      label: 'FAQ',
      items: [
        'faq/-algorithm-change-log',
        'faq/-answer-streaming',
        'faq/-can-i-add-macros-canned-or-stock-responses-to-my-ai-agent',
        'faq/-can-i-give-my-agent-a-personality-adjust-the-tone-or-customize-the-prompt',
        'faq/-can-i-have-multiple-ai-agents-multiple-brands-or-multiple-knowledge-bases',
        'faq/-can-i-route-tickets-to-different-agents',
        'faq/-can-i-use-my-own-openai-assistant-or-custom-gpt',
        'faq/-can-i-use-the-ai-agent-within-a-mobile-app',
        'faq/-does-it-get-smarter-the-more-conversations-it-has',
        'faq/-feature-suggestions',
        'faq/-how-can-i-test-my-ai-agent-without-it-responding-to-customers',
        'faq/-how-can-i-test-the-accuracy-of-my-ai-agents-answers',
        'faq/-how-does-it-work',
        'faq/-large-language-models-llms',
        'faq/-my-askai-vs-chatgpt',
        'faq/-my-askai-vs-fine-tuning',
        'faq/-my-website-has-dynamic-content-can-i-use-my-askai',
        'faq/-temperature',
        'faq/-what-are-your-social-accounts',
        'faq/-what-if-it-cant-answer',
        'faq/-what-is-the-difference-between-my-askai-and-my-askai-classic',
        'faq/-which-messages-will-my-ai-agent-respond-to',
        'faq/-will-it-answer-questions-about-competitors-products',
        'faq/-will-it-make-things-up'
      ]
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      items: [
        'troubleshooting/chat-bubble-not-visible',
        'troubleshooting/issue-connecting-your-live-chat-widget',
        'troubleshooting/login',
        'troubleshooting/oops-there-has-been-an-error',
        'troubleshooting/slow-responses',
        'troubleshooting/website-not-added',
        'troubleshooting/why-cant-it-answer'
      ]
    }
  ]
};

export default sidebars;
